const SET_OPTIONS = "SET_OPTIONS";
const GET_FORM_DATA = "GET_FORM_DATA";
const GET_RESPONSE = "GET_RESPONSE";
const REDIRECT_AFTER_SUBMIT = "REDIRECT_AFTER_SUBMIT";
const MESSAGE_MODAL = "MESSAGE_MODAL";
const GET_MESSAGE_RES = "GET_MESSAGE_RES";

export {
  SET_OPTIONS,
  GET_FORM_DATA,
  GET_RESPONSE,
  REDIRECT_AFTER_SUBMIT,
  MESSAGE_MODAL,
  GET_MESSAGE_RES,
};
